#!/usr/bin/env bash
# A# Configure your Nginx server so that /redirect_me is redirecting to another page

# Update Ubuntu and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Start the Nginx service
sudo service nginx start

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 'Nginx HTTPS'

# Create an index.html file
echo 'Hello World!' | sudo tee /var/www/html/index.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-available/default

# Restart Nginx service
sudo service nginx restart
