#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

# Install Nginx if not already installed
sudo apt-get -y update
sudo apt-get -y install nginx

# Start the Nginx service
sudo service nginx start

# Create a backup of the default configuration
# sudo cp /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default_backup

# Add a location block for the redirection in the Nginx default configuration
new_string="\tserver_name _;\n \trewrite ^/redirect_me$ http://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n \trewrite ^/\
redirect_me/$ http://www.youtube.com/watch?v=QH2-TGUlwu4 permanent; "

sudo sed -i "s|^[^#].*server_name.*;|$new_string|" /etc/nginx/sites-enabled/default;

# Restart Nginx to apply the changes
sudo service nginx restart
