#!/bin/bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

# Install Nginx if not already installed
sudo apt-get -y update
sudo apt-get -y install nginx

# Start the Nginx service
sudo service nginx start

# Create a backup of the default configuration
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default_backup

# Add a location block for the redirection in the Nginx default configuration
redirection_string="server {\n\tlisten 80 default_server;\n\tlisten [::]:80 default_server;\n\n\troot /var/www/html;\n\tindex index.html index.htm index.nginx-debian.html;\n\n\tserver_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {\n\t\ttry_files \$uri \$uri/ =404;\n\t}\n}"

sudo ed -i "s#.*#$redirection_string#" /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart
