#!/usr/bin/env bash
# A# Configure your Nginx server so that /redirect_me is redirecting to another page

# Update Ubuntu and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Start the Nginx service
sudo service nginx start

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 'Nginx HTTPS'

# Create an index.html file
echo 'Hello World!' | sudo tee /var/www/html/index.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Creating a 404 Custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

string_404="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# Restart Nginx services
sudo service nginx restart
