#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely with 2 second sleeps
# When SIGTERM is received, displays "I am invicible!!!"

function handle_sigterm() {
	echo "I am invincible!!!"
}

trap 'handle_sigterm' SIGTERM

while true; do
	echo "To infinity and beyond!"
	sleep 2
done
