#!/usr/bin/env bash
# This shell script print Best School 10 times
# But prints "Hi" on the ninth iteration

count=1

while [ $count -le 10 ]; do
	echo "Best School"
	if [ $count == 9 ]
	then
		echo "Hi"
	fi
	count=$((count + 1))
done
