#!/usr/bin/env bash
# This shell script print Best School 10 times
# But prints "bad luck" and "good luck" 
# on the fourth and eight iteration respectively.

count=1

while [ $count -le 10 ]; do
        if [ $count == 4 ]; then
                echo "bad luck"

	elif [ $count == 8 ]; then
		echo "good luck"

        else
                echo "Best School"
        fi
	count=$((count + 1))
done
