#!/usr/bin/env bash
# Prints numbers from 1-20 and include some superstitious facts
# for number == 4: bad luck from China
# for number == 9: bad luck from Japan
# for number == 17: bad luck from Italy
# Uses while loop and case

number=1
while [ $number -le 20 ]; do
	echo $number
	case $number in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	number=$((number + 1))
done
