#!/usr/bin/env bash
# Lists and print the non-hidden items in current working directory
# Only print filenames after '-'

for file in *; do
	if [[ -f $file && $file != .* ]]; then
		name=$(echo "$file" | cut -d '-' -f 2-)
		echo "$name"
	fi
done
