#!/usr/bin/env bash
# Tests and gives the information about a file
# Uses 'test' command

file_path="school"

if test -e "$file_path"; then
	echo "school file exists"
	if test -s "$file_path"; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if test -f "$file_path"; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
