#!/usr/bin/env bash
# make your fix short and sweet. (1-run_nginx_as_nginx)
sudo service nginx stop
sudo sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default
sed -i 's/listen [::]:80 default_server;/listen [::]:8080 default_server;/g' /etc/nginx/sites-available/default
sudo service nginx start
